name: Deploy to EC2

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # 1. Install Backend Dependencies
      - name: Install Backend Dependencies
        run: |
          npm install  # Backend in root, no need to cd

      # 2. Deploy Pre-Built Frontend
      - name: Deploy Pre-Built Frontend
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -r client/build/* /var/www/html/

      # 3. Deploy Backend with PM2
      - name: Deploy Backend with PM2
        run: |
          pm2 stop all || true  # Manage backend app from root
          pm2 start index.js --name api
          pm2 restart api
